/**
 * Config Snapshot Schema Contract
 *
 * config_snapshot: SOLO configuración (dimensiones, selección de SKUs/ids, opciones).
 * NO debe contener costos ni totales (cost/total keys are stripped before save).
 *
 * bom_preview_snapshot: Generado por SQL (build_bom_preview_snapshot + calculate_configured_product_totals).
 * Fuente de verdad para totales: totals.roll_msrp_total, totals.bom_total, totals.total_msrp,
 * totals.roll_total_cost, totals.bom_total_cost, totals.unit_product_cost, totals.total_cost.
 *
 * Fuente de precios/costos de catálogo: CatalogItemsMSRP (msrp, pricing_cost_exw/total_cost).
 */

/** Keys that must NEVER be stored in config_snapshot (costs, totals, pricing). */
export const CONFIG_SNAPSHOT_COST_KEYS = new Set([
  'roll_total_cost_landed',
  'bom_total_cost_landed',
  'accessories_total_cost_landed',
  'unit_product_cost_landed',
  'unit_labor_cost',
  'total_cost_landed_without_labor',
  'total_cost_with_labor',
  'roll_total_cost',
  'bom_total_cost',
  'accessories_total_cost',
  'roll_msrp_total',
  'bom_total',
  'accessories_total',
  'labor_amount',
  'labor_msrp',
  'total_msrp',
  'unit_msrp_total',
  'msrp_product_subtotal',
  'unit_dealer_price',
  'dealer_price_total',
  'unit_dealer_price_snapshot',
  'dealer_price_total_snapshot',
  'catalog_dealer_unit_snapshot',
  'roll_cost_snapshot',
  'bom_cost_snapshot',
  'labor_cost_snapshot',
  'unit_cost_total_snapshot',
  'bom_preview_snapshot', // Generated by SQL, never from frontend
  'configured_product_totals',
  'effectiveCosts',
  'effectiveTotals',
]);

/** Keys to skip when spreading config_snapshot into config (preserve display values from CP/bom_preview). */
export const CONFIG_SNAPSHOT_SKIP_ON_SPREAD = new Set([
  ...CONFIG_SNAPSHOT_COST_KEYS,
  'productType',
  'product_type_id',
  'productTypeId',
  'quote_line_id',
  'configured_product_id',
]);

/**
 * Removes cost/total keys from an object before persisting as config_snapshot.
 * Call this whenever building config_snapshot for create_configured_product_and_bom_preview.
 */
export function stripCostKeys<T extends Record<string, unknown>>(obj: T): T {
  if (!obj || typeof obj !== 'object') return obj;
  const result = { ...obj } as Record<string, unknown>;
  for (const key of CONFIG_SNAPSHOT_COST_KEYS) {
    if (key in result) delete result[key];
  }
  return result as T;
}

/**
 * Returns a shallow copy of obj with only keys allowed in config_snapshot.
 * Use when building config_snapshot from a mixed config that may contain display/cost keys.
 */
export function configSnapshotOnly<T extends Record<string, unknown>>(obj: T): Record<string, unknown> {
  if (!obj || typeof obj !== 'object') return {};
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (!CONFIG_SNAPSHOT_COST_KEYS.has(k) && v !== undefined && v !== null) {
      result[k] = v;
    }
  }
  return result;
}
