import { supabase } from './supabase/client';

/**
 * Generates the next sequential number for a given document type
 * Format: QT/PR PREFIX-NNNNN (e.g. QT-00100, PR-00100). SO is generated by DB trigger as SO-NNNNN-YYMMDD (e.g. SO-00100-260225).
 * QT/PR/SO: sequence starts at 100 (00100, 00101, ...) with 5 digits.
 * When dealerId is provided, numbering is per dealer (each dealer has independent sequence).
 *
 * @param prefix - The prefix for the number (e.g., 'QT' for Quotes)
 * @param tableName - The table name to query
 * @param numberField - The field name that contains the number
 * @param organizationId - The organization ID to filter by
 * @param dealerId - Optional. When set, sequence is per dealer (Quotes/Proposals)
 */
export async function generateNextSequentialNumber(
  prefix: string,
  tableName: string,
  numberField: string,
  organizationId: string,
  _dealerId?: string | null  // kept for API compatibility but ignored — numbering is org-wide
): Promise<string> {
  try {
    // Always query org-wide (no dealer filter) so numbers are unique across all dealers
    const { data, error } = await supabase
      .from(tableName)
      .select(numberField)
      .eq('organization_id', organizationId)
      .eq('deleted', false)
      .not(numberField, 'is', null)
      .order('created_at', { ascending: false });

    if (error) throw error;

    const minStart = 100;
    const padLength = 5;
    const pattern = new RegExp(`^${prefix}-(\\d+)$`);

    let maxNumber = minStart - 1;
    if (data && data.length > 0) {
      for (const row of data) {
        const no = (row as any)[numberField];
        if (!no) continue;
        const match = String(no).match(pattern);
        if (match && match[1] != null) {
          const n = parseInt(match[1], 10);
          if (n > maxNumber) maxNumber = n;
        }
      }
    }

    return `${prefix}-${String(Math.max(minStart, maxNumber + 1)).padStart(padLength, '0')}`;
  } catch (err) {
    console.error(`Error generating ${prefix} number:`, err);
    return `${prefix}-${Date.now().toString().slice(-6)}`;
  }
}

/**
 * Generates the next Quote number. Per dealer when dealerId is provided.
 */
export async function generateNextQuoteNumber(
  organizationId: string,
  dealerId?: string | null
): Promise<string> {
  return generateNextSequentialNumber('QT', 'Quotes', 'quote_no', organizationId, dealerId);
}

/**
 * Generates the next Order number
 */
export async function generateNextOrderNumber(organizationId: string): Promise<string> {
  return generateNextSequentialNumber('OR', 'SaleOrders', 'order_no', organizationId);
}

/**
 * Generates the next Invoice number (org-wide). Format: INV-NNNNN.
 */
export async function generateNextInvoiceNumber(organizationId: string): Promise<string> {
  return generateNextSequentialNumber('INV', 'DealerInvoices', 'invoice_number', organizationId);
}

export async function generateNextBillNumber(organizationId: string): Promise<string> {
  return generateNextSequentialNumber('BILL', 'VendorBills', 'bill_number', organizationId);
}

export async function generateNextVendorCreditNumber(organizationId: string): Promise<string> {
  return generateNextSequentialNumber('VCR', 'VendorCredits', 'credit_number', organizationId);
}

/**
 * Generates the next Purchase Order number (org-wide). Format: PO-NNNNN.
 * PurchaseOrders table has no deleted column; query all rows with po_number.
 */
export async function generateNextPurchaseOrderNumber(organizationId: string): Promise<string> {
  try {
    const { data, error } = await supabase
      .from('PurchaseOrders')
      .select('po_number')
      .eq('organization_id', organizationId)
      .not('po_number', 'is', null)
      .order('created_at', { ascending: false });

    if (error) throw error;

    const minStart = 100;
    const padLength = 5;
    const pattern = /^PO-(\d+)$/;
    let maxNumber = minStart - 1;

    if (data && data.length > 0) {
      for (const row of data) {
        const no = (row as { po_number: string | null }).po_number;
        if (!no) continue;
        const match = String(no).match(pattern);
        if (match && match[1] != null) {
          const n = parseInt(match[1], 10);
          if (n > maxNumber) maxNumber = n;
        }
      }
    }

    return `PO-${String(Math.max(minStart, maxNumber + 1)).padStart(padLength, '0')}`;
  } catch (err) {
    console.error('Error generating PO number:', err);
    return `PO-${Date.now().toString().slice(-6)}`;
  }
}

/** Minimum proposal number (PR-00100, PR-00101, ...) */
const PROPOSAL_NUMBER_START = 100;
const PROPOSAL_PREFIX = 'PR';

/**
 * Generates the next Proposal number. Per dealer when dealerId is provided.
 * Format: PR-NNNNN starting at PR-00100. Independent from Quote (QT) numbering.
 */
export async function generateNextProposalNumber(
  organizationId: string,
  dealerId: string
): Promise<string> {
  try {
    const { data, error } = await supabase
      .from('Proposals')
      .select('proposal_no')
      .eq('organization_id', organizationId)
      .eq('dealer_id', dealerId)
      .eq('deleted', false)
      .not('proposal_no', 'is', null);

    if (error) throw error;

    let nextNumber = PROPOSAL_NUMBER_START;
    if (data && data.length > 0) {
      const numbers = (data as { proposal_no: string | null }[])
        .map((row: { proposal_no: string | null }) => {
          const no = row.proposal_no;
          if (!no) return null;
          const m = String(no).match(/^(?:PR|PRO)-(\d+)$/i);
          return m ? parseInt(m[1], 10) : null;
        })
        .filter((n: number | null): n is number => n != null);
      if (numbers.length > 0) {
        nextNumber = Math.max(PROPOSAL_NUMBER_START, Math.max(...numbers) + 1);
      }
    }

    return `${PROPOSAL_PREFIX}-${String(nextNumber).padStart(5, '0')}`;
  } catch (err) {
    console.error('Error generating PR number:', err);
    return `${PROPOSAL_PREFIX}-${String(PROPOSAL_NUMBER_START + Math.floor(Math.random() * 900)).padStart(5, '0')}`;
  }
}










