-- ArquiproductosERP baseline schema
-- Naming: PascalCase tables, snake_case columns.

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- PHASE 1: Core
-- ---------------------------------------------------------------------------
create table if not exists public."Companies" (
  id bigint generated by default as identity primary key,
  name text not null,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null,
  modifier uuid null
);

create table if not exists public."UserProfiles" (
  id uuid primary key references auth.users (id) on delete cascade,
  company_id bigint not null references public."Companies" (id),
  first_name text not null,
  last_name text not null,
  role text not null check (role in ('ADMIN', 'MANAGER', 'INTERNAL_USER', 'DISTRIBUTOR_USER', 'VIEW_ONLY')),
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create index if not exists userprofiles_company_idx on public."UserProfiles" (company_id);

insert into public."Companies" (id, name)
values (1, 'Arquiproductos')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- PHASE 2: Directory
-- ---------------------------------------------------------------------------
create table if not exists public."DirectoryCustomers" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  code text,
  email text,
  phone text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."DirectoryVendors" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  code text,
  email text,
  phone text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."DirectoryContractors" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  code text,
  email text,
  phone text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."DirectoryEmployees" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  title text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."DirectorySites" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  customer_id uuid null references public."DirectoryCustomers" (id),
  vendor_id uuid null references public."DirectoryVendors" (id),
  contractor_id uuid null references public."DirectoryContractors" (id),
  address text,
  city text,
  state text,
  country text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."DirectoryContacts" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  customer_id uuid null references public."DirectoryCustomers" (id),
  vendor_id uuid null references public."DirectoryVendors" (id),
  contractor_id uuid null references public."DirectoryContractors" (id),
  site_id uuid null references public."DirectorySites" (id),
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

-- ---------------------------------------------------------------------------
-- PHASE 3: Inventory (skeleton)
-- ---------------------------------------------------------------------------
create table if not exists public."InventoryWarehouses" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  code text,
  location text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."InventoryPurchaseOrders" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  vendor_id uuid not null references public."DirectoryVendors" (id),
  warehouse_id uuid null references public."InventoryWarehouses" (id),
  po_number text not null,
  status text not null default 'DRAFT',
  order_date date not null default current_date,
  expected_date date,
  notes text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create unique index if not exists inv_po_unique on public."InventoryPurchaseOrders" (company_id, po_number);

create table if not exists public."InventoryPurchaseOrderLines" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  purchase_order_id uuid not null references public."InventoryPurchaseOrders" (id) on delete cascade,
  catalog_item_id uuid null,
  item_sku text,
  item_name text,
  quantity numeric(14, 4) not null default 0,
  unit_cost numeric(14, 4) not null default 0,
  uom text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."InventoryReceipts" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  purchase_order_id uuid null references public."InventoryPurchaseOrders" (id),
  warehouse_id uuid null references public."InventoryWarehouses" (id),
  receipt_date date not null default current_date,
  reference text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."InventoryTransactions" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  warehouse_id uuid null references public."InventoryWarehouses" (id),
  receipt_id uuid null references public."InventoryReceipts" (id),
  purchase_order_line_id uuid null references public."InventoryPurchaseOrderLines" (id),
  transaction_type text not null check (transaction_type in ('RECEIPT', 'ADJUSTMENT', 'TRANSFER', 'ISSUE')),
  catalog_item_id uuid null,
  item_sku text,
  item_name text,
  quantity numeric(14, 4) not null default 0,
  uom text,
  unit_cost numeric(14, 4) default 0,
  notes text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."InventoryAdjustments" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  warehouse_id uuid null references public."InventoryWarehouses" (id),
  reason text,
  reference text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

-- ---------------------------------------------------------------------------
-- PHASE 4: Financials (skeleton)
-- ---------------------------------------------------------------------------
create table if not exists public."FinancialInvoices" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  customer_id uuid not null references public."DirectoryCustomers" (id),
  site_id uuid null references public."DirectorySites" (id),
  invoice_number text not null,
  status text not null default 'DRAFT',
  invoice_date date not null default current_date,
  due_date date,
  currency text not null default 'USD',
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create unique index if not exists financial_invoice_unique on public."FinancialInvoices" (company_id, invoice_number);

create table if not exists public."FinancialInvoiceLines" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  invoice_id uuid not null references public."FinancialInvoices" (id) on delete cascade,
  catalog_item_id uuid null,
  description text not null,
  quantity numeric(14, 4) not null default 1,
  uom text,
  unit_price numeric(14, 4) not null default 0,
  total_price numeric(14, 4) not null default 0,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."FinancialPayments" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  customer_id uuid not null references public."DirectoryCustomers" (id),
  invoice_id uuid null references public."FinancialInvoices" (id),
  payment_date date not null default current_date,
  amount numeric(14, 4) not null default 0,
  currency text not null default 'USD',
  method text,
  reference text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."FinancialCredits" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  customer_id uuid not null references public."DirectoryCustomers" (id),
  invoice_id uuid null references public."FinancialInvoices" (id),
  credit_date date not null default current_date,
  amount numeric(14, 4) not null default 0,
  currency text not null default 'USD',
  reason text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

-- ---------------------------------------------------------------------------
-- PHASE 5: Settings
-- ---------------------------------------------------------------------------
create table if not exists public."SettingsItemCategories" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  code text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."SettingsItemSubCategories" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  category_id uuid not null references public."SettingsItemCategories" (id),
  name text not null,
  code text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."SettingsUnitsOfMeasure" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  abbreviation text not null,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."SettingsPaymentTerms" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  days integer not null default 0,
  description text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."SettingsTaxCodes" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  name text not null,
  rate numeric(8, 4) not null default 0,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

create table if not exists public."SettingsCurrencies" (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies" (id),
  code text not null,
  name text not null,
  symbol text,
  deleted boolean not null default false,
  archived boolean not null default false,
  created_date timestamptz not null default now(),
  modified_date timestamptz not null default now(),
  creator uuid null references auth.users (id),
  modifier uuid null references auth.users (id)
);

-- ---------------------------------------------------------------------------
-- TODO: Add RLS policies per role and company scoping once Supabase auth is configured.
-- Policies will ensure users only access rows for their company_id.

