-- ========================================
-- DIAGNOSTIC: Root Cause Analysis for Missing BOM Components
-- ========================================
-- This script diagnoses why only fabrics appear in the BOM
-- It checks the entire pipeline from Quote → QuoteLineComponents → BomInstanceLines
-- ========================================
-- INSTRUCTIONS:
-- 1. Replace 'SO-000003' with your actual Sale Order number
-- 2. Run this in Supabase SQL Editor
-- 3. Share the results
-- ========================================

-- ========================================
-- STEP 1: Check QuoteLineComponents (What was generated by generate_configured_bom_for_quote_line)
-- ========================================
-- This shows what components were actually generated for the quote line

SELECT 
  'STEP 1: QuoteLineComponents Generated' as step,
  qlc.id,
  qlc.component_role,
  qlc.source,
  qlc.qty,
  qlc.uom,
  ci.sku,
  ci.item_name,
  ci.is_fabric
FROM "SaleOrders" so
  INNER JOIN "SaleOrderLines" sol ON sol.sale_order_id = so.id AND sol.deleted = false
  INNER JOIN "QuoteLines" ql ON ql.id = sol.quote_line_id AND ql.deleted = false
  LEFT JOIN "QuoteLineComponents" qlc ON qlc.quote_line_id = ql.id 
    AND qlc.source = 'configured_component' 
    AND qlc.deleted = false
  LEFT JOIN "CatalogItems" ci ON ci.id = qlc.catalog_item_id
WHERE so.sale_order_no = 'SO-000003' -- CHANGE THIS
  AND so.deleted = false
ORDER BY 
  CASE qlc.component_role
    WHEN 'fabric' THEN 1
    WHEN 'operating_system_drive' THEN 2
    WHEN 'tube' THEN 3
    WHEN 'bracket' THEN 4
    WHEN 'bottom_bar' THEN 5
    WHEN 'cassette' THEN 6
    WHEN 'side_channel' THEN 7
    ELSE 99
  END,
  ci.sku;

-- EXPECTED: Multiple rows with different component_role values
-- If only 'fabric' appears, the problem is in generate_configured_bom_for_quote_line

-- ========================================
-- STEP 2: Check BOMTemplate Components (What SHOULD be generated)
-- ========================================
-- This shows what components are configured in the BOMTemplate

WITH sale_order_data AS (
  SELECT DISTINCT sol.product_type_id, sol.organization_id
  FROM "SaleOrders" so
    INNER JOIN "SaleOrderLines" sol ON sol.sale_order_id = so.id AND sol.deleted = false
  WHERE so.sale_order_no = 'SO-000003' -- CHANGE THIS
    AND so.deleted = false
)
SELECT 
  'STEP 2: BOMTemplate Components' as step,
  bc.id as bom_component_id,
  bc.component_role,
  bc.block_type,
  bc.block_condition,
  bc.applies_color,
  bc.hardware_color,
  bc.auto_select,
  bc.sku_resolution_rule,
  bc.qty_per_unit,
  bc.uom,
  bc.component_item_id,
  ci.sku,
  ci.item_name,
  CASE 
    WHEN bc.component_item_id IS NULL AND bc.auto_select = false THEN '❌ MISSING: No item_id and not auto_select'
    WHEN bc.component_item_id IS NULL AND bc.auto_select = true AND bc.sku_resolution_rule IS NULL THEN '❌ MISSING: auto_select=true but no resolution rule'
    WHEN bc.component_item_id IS NOT NULL THEN '✅ HAS: Direct item_id'
    WHEN bc.auto_select = true AND bc.sku_resolution_rule IS NOT NULL THEN '✅ HAS: Auto-select with rule'
    ELSE '⚠️ UNKNOWN'
  END as resolution_status
FROM sale_order_data sod
  INNER JOIN "BOMTemplates" bt ON bt.product_type_id = sod.product_type_id 
    AND bt.organization_id = sod.organization_id
    AND bt.deleted = false
    AND bt.active = true
  LEFT JOIN "BOMComponents" bc ON bc.bom_template_id = bt.id 
    AND bc.deleted = false
  LEFT JOIN "CatalogItems" ci ON ci.id = bc.component_item_id
ORDER BY bc.sequence_order, bc.component_role;

-- EXPECTED: Multiple rows with different component_role values
-- If only 'fabric' appears, the BOMTemplate is incomplete

-- ========================================
-- STEP 3: Check QuoteLine Configuration (What was passed to generate_configured_bom)
-- ========================================
-- This shows the configuration that was used to generate the BOM

SELECT 
  'STEP 3: QuoteLine Configuration' as step,
  ql.id as quote_line_id,
  ql.product_type_id,
  pt.code as product_type_code,
  ql.drive_type,
  ql.bottom_rail_type,
  ql.cassette,
  ql.cassette_type,
  ql.side_channel,
  ql.side_channel_type,
  ql.hardware_color,
  ql.width_m,
  ql.height_m,
  ql.qty
FROM "SaleOrders" so
  INNER JOIN "SaleOrderLines" sol ON sol.sale_order_id = so.id AND sol.deleted = false
  INNER JOIN "QuoteLines" ql ON ql.id = sol.quote_line_id AND ql.deleted = false
  LEFT JOIN "ProductTypes" pt ON pt.id = ql.product_type_id
WHERE so.sale_order_no = 'SO-000003' -- CHANGE THIS
  AND so.deleted = false;

-- EXPECTED: All configuration fields should have values (not NULL)
-- If drive_type, cassette, hardware_color are NULL, the configuration wasn't saved correctly

-- ========================================
-- STEP 4: Check Block Condition Matching Logic
-- ========================================
-- This simulates what the generate_configured_bom function should do
-- to see which components should match

WITH quote_line_config AS (
  SELECT 
    ql.id as quote_line_id,
    ql.product_type_id,
    ql.organization_id,
    ql.drive_type,
    ql.bottom_rail_type,
    ql.cassette,
    ql.cassette_type,
    ql.side_channel,
    ql.side_channel_type,
    ql.hardware_color
  FROM "SaleOrders" so
    INNER JOIN "SaleOrderLines" sol ON sol.sale_order_id = so.id AND sol.deleted = false
    INNER JOIN "QuoteLines" ql ON ql.id = sol.quote_line_id AND ql.deleted = false
  WHERE so.sale_order_no = 'SO-000003' -- CHANGE THIS
    AND so.deleted = false
  LIMIT 1
),
bom_components AS (
  SELECT 
    bc.*,
    bt.id as bom_template_id
  FROM quote_line_config qlc
    INNER JOIN "BOMTemplates" bt ON bt.product_type_id = qlc.product_type_id 
      AND bt.organization_id = qlc.organization_id
      AND bt.deleted = false
      AND bt.active = true
    LEFT JOIN "BOMComponents" bc ON bc.bom_template_id = bt.id 
      AND bc.deleted = false
)
SELECT 
  'STEP 4: Block Condition Matching' as step,
  bc.component_role,
  bc.block_type,
  bc.block_condition,
  bc.applies_color,
  bc.hardware_color as bom_hardware_color,
  qlc.drive_type as config_drive_type,
  qlc.bottom_rail_type as config_bottom_rail_type,
  qlc.cassette as config_cassette,
  qlc.cassette_type as config_cassette_type,
  qlc.side_channel as config_side_channel,
  qlc.side_channel_type as config_side_channel_type,
  qlc.hardware_color as config_hardware_color,
  CASE 
    -- Check drive_type match
    WHEN bc.block_condition->>'drive_type' IS NOT NULL 
      AND bc.block_condition->>'drive_type' != qlc.drive_type THEN '❌ BLOCKED: drive_type mismatch'
    -- Check bottom_rail_type match
    WHEN bc.block_condition->>'bottom_rail_type' IS NOT NULL 
      AND bc.block_condition->>'bottom_rail_type' != qlc.bottom_rail_type THEN '❌ BLOCKED: bottom_rail_type mismatch'
    -- Check cassette match
    WHEN bc.block_condition->>'cassette' IS NOT NULL 
      AND (bc.block_condition->>'cassette')::boolean != COALESCE(qlc.cassette, false) THEN '❌ BLOCKED: cassette mismatch'
    -- Check cassette_type match
    WHEN bc.block_condition->>'cassette_type' IS NOT NULL 
      AND (COALESCE(qlc.cassette, false) = false OR bc.block_condition->>'cassette_type' != qlc.cassette_type) THEN '❌ BLOCKED: cassette_type mismatch'
    -- Check side_channel match
    WHEN bc.block_condition->>'side_channel' IS NOT NULL 
      AND (bc.block_condition->>'side_channel')::boolean != COALESCE(qlc.side_channel, false) THEN '❌ BLOCKED: side_channel mismatch'
    -- Check side_channel_type match
    WHEN bc.block_condition->>'side_channel_type' IS NOT NULL 
      AND (COALESCE(qlc.side_channel, false) = false OR bc.block_condition->>'side_channel_type' != qlc.side_channel_type) THEN '❌ BLOCKED: side_channel_type mismatch'
    -- Check hardware_color match
    WHEN bc.applies_color = true 
      AND bc.hardware_color != qlc.hardware_color THEN '❌ BLOCKED: hardware_color mismatch'
    -- Check if component has item_id or auto_select
    WHEN bc.component_item_id IS NULL 
      AND (bc.auto_select = false OR bc.sku_resolution_rule IS NULL) THEN '❌ BLOCKED: No item_id and cannot auto-select'
    ELSE '✅ SHOULD MATCH'
  END as match_status
FROM bom_components bc
  CROSS JOIN quote_line_config qlc
ORDER BY 
  CASE 
    -- Check drive_type match
    WHEN bc.block_condition->>'drive_type' IS NOT NULL 
      AND bc.block_condition->>'drive_type' != qlc.drive_type THEN 2
    -- Check bottom_rail_type match
    WHEN bc.block_condition->>'bottom_rail_type' IS NOT NULL 
      AND bc.block_condition->>'bottom_rail_type' != qlc.bottom_rail_type THEN 2
    -- Check cassette match
    WHEN bc.block_condition->>'cassette' IS NOT NULL 
      AND (bc.block_condition->>'cassette')::boolean != COALESCE(qlc.cassette, false) THEN 2
    -- Check cassette_type match
    WHEN bc.block_condition->>'cassette_type' IS NOT NULL 
      AND (COALESCE(qlc.cassette, false) = false OR bc.block_condition->>'cassette_type' != qlc.cassette_type) THEN 2
    -- Check side_channel match
    WHEN bc.block_condition->>'side_channel' IS NOT NULL 
      AND (bc.block_condition->>'side_channel')::boolean != COALESCE(qlc.side_channel, false) THEN 2
    -- Check side_channel_type match
    WHEN bc.block_condition->>'side_channel_type' IS NOT NULL 
      AND (COALESCE(qlc.side_channel, false) = false OR bc.block_condition->>'side_channel_type' != qlc.side_channel_type) THEN 2
    -- Check hardware_color match
    WHEN bc.applies_color = true 
      AND bc.hardware_color != qlc.hardware_color THEN 2
    -- Check if component has item_id or auto_select
    WHEN bc.component_item_id IS NULL 
      AND (bc.auto_select = false OR bc.sku_resolution_rule IS NULL) THEN 2
    ELSE 1
  END,
  bc.component_role;

-- EXPECTED: Multiple rows with '✅ SHOULD MATCH' status
-- If most rows show '❌ BLOCKED', the block_condition logic is too restrictive

-- ========================================
-- STEP 5: Compare QuoteLineComponents vs BomInstanceLines
-- ========================================
-- This shows what was copied from QuoteLineComponents to BomInstanceLines

SELECT 
  'STEP 5: QuoteLineComponents vs BomInstanceLines' as step,
  'QuoteLineComponents' as source,
  qlc.component_role,
  qlc.qty,
  qlc.uom,
  ci.sku,
  ci.item_name
FROM "SaleOrders" so
  INNER JOIN "SaleOrderLines" sol ON sol.sale_order_id = so.id AND sol.deleted = false
  INNER JOIN "QuoteLines" ql ON ql.id = sol.quote_line_id AND ql.deleted = false
  LEFT JOIN "QuoteLineComponents" qlc ON qlc.quote_line_id = ql.id 
    AND qlc.source = 'configured_component' 
    AND qlc.deleted = false
  LEFT JOIN "CatalogItems" ci ON ci.id = qlc.catalog_item_id
WHERE so.sale_order_no = 'SO-000003' -- CHANGE THIS
  AND so.deleted = false

UNION ALL

SELECT 
  'STEP 5: QuoteLineComponents vs BomInstanceLines' as step,
  'BomInstanceLines' as source,
  bil.part_role as component_role,
  bil.qty,
  bil.uom,
  ci.sku,
  ci.item_name
FROM "SaleOrders" so
  INNER JOIN "SaleOrderLines" sol ON sol.sale_order_id = so.id AND sol.deleted = false
  INNER JOIN "BomInstances" bi ON bi.sale_order_line_id = sol.id AND bi.deleted = false
  INNER JOIN "BomInstanceLines" bil ON bil.bom_instance_id = bi.id AND bil.deleted = false
  LEFT JOIN "CatalogItems" ci ON ci.id = bil.resolved_part_id
WHERE so.sale_order_no = 'SO-000003' -- CHANGE THIS
  AND so.deleted = false
ORDER BY source, component_role, sku;

-- EXPECTED: Both sources should have the same components
-- If QuoteLineComponents has more rows than BomInstanceLines, the copy process failed

-- ========================================
-- INTERPRETATION GUIDE
-- ========================================
--
-- IF STEP 1 shows only 'fabric' in QuoteLineComponents:
--   → Problem: generate_configured_bom_for_quote_line only generated fabrics
--   → Root Cause: Either BOMTemplate is incomplete OR block_condition filtering is too restrictive
--   → Fix: Check STEP 2 and STEP 4
--
-- IF STEP 2 shows only 'fabric' in BOMTemplate:
--   → Problem: BOMTemplate is incomplete
--   → Fix: Run seed migration or create BOMComponents manually for all component types
--
-- IF STEP 3 shows NULL values for drive_type, cassette, hardware_color:
--   → Problem: Configuration not being saved to QuoteLines
--   → Fix: Check QuoteNew.tsx handleProductConfigComplete function
--
-- IF STEP 4 shows most components as '❌ BLOCKED':
--   → Problem: Block condition logic is too restrictive or configuration doesn't match
--   → Fix: Review block_condition values in BOMComponents and ensure QuoteLine config matches
--
-- IF STEP 5 shows QuoteLineComponents has more rows than BomInstanceLines:
--   → Problem: Copy process from QuoteLineComponents to BomInstanceLines failed
--   → Fix: Check on_quote_approved_create_operational_docs function (line 808-876)
--
-- ========================================

