import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase/client';
import { useOrganizationContext } from '../context/OrganizationContext';

/**
 * Company shape canónico para UI
 */
export interface Company {
  id: string;
  organization_id: string;
  company_no: string | null;
  company_name: string;
  company_email: string | null;
  company_phone: string | null;
  status: string;
  deleted: boolean;
  created_at?: string;
  updated_at?: string;
}

/**
 * Input para crear Company
 */
export interface CreateCompanyInput {
  company_name: string;
  company_email?: string;
  company_phone?: string;
  status?: string;
}

/**
 * Input para actualizar Company
 */
export interface UpdateCompanyInput {
  company_name?: string;
  company_email?: string;
  company_phone?: string;
  status?: string;
}

/**
 * Hook para gestionar Companies (dealers/empresas que cotizan)
 * Companies pertenecen a Organizations
 */
export function useCompanies() {
  const [companies, setCompanies] = useState<Company[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { activeOrganizationId } = useOrganizationContext();

  /**
   * Fetch companies
   */
  const fetchCompanies = useCallback(async () => {
    if (!activeOrganizationId) {
      setCompanies([]);
      setIsLoading(false);
      setError(null);
      return;
    }

    try {
      setIsLoading(true);
      setError(null);

      const { data, error: queryError } = await supabase
        .from('Companies')
        .select('id, organization_id, company_no, company_name, company_email, company_phone, status, deleted, created_at, updated_at')
        .eq('organization_id', activeOrganizationId)
        .eq('deleted', false)
        .order('created_at', { ascending: false });

      if (queryError) {
        throw queryError;
      }

      const mapped: Company[] = (data || []).map((row: any) => ({
        id: row.id,
        organization_id: row.organization_id,
        company_no: row.company_no ? row.company_no.toString().trim() : null,
        company_name: (row.company_name || '').toString().trim(),
        company_email: row.company_email ? row.company_email.toString().trim().toLowerCase() : null,
        company_phone: row.company_phone ? row.company_phone.toString().trim() : null,
        status: row.status || 'active',
        deleted: row.deleted || false,
        created_at: row.created_at || undefined,
        updated_at: row.updated_at || undefined,
      }));

      if (import.meta.env.DEV) {
        console.log('[useCompanies] Fetched companies:', {
          count: mapped.length,
          sample: mapped[0] || null,
        });
      }

      setCompanies(mapped);
    } catch (err: any) {
      const errorMessage = err?.message || 'Error loading companies';
      console.error('[useCompanies] Error:', errorMessage, err);
      setError(errorMessage);
      setCompanies([]);
    } finally {
      setIsLoading(false);
    }
  }, [activeOrganizationId]);

  /**
   * Create company
   */
  const createCompany = useCallback(async (input: CreateCompanyInput): Promise<Company> => {
    if (!activeOrganizationId) {
      throw new Error('No active organization');
    }

    try {
      // IMPORTANT: Do NOT send company_no - it will be auto-generated by the trigger
      const payload: any = {
        organization_id: activeOrganizationId,
        company_name: input.company_name.trim(),
        company_email: input.company_email?.trim().toLowerCase() || null,
        company_phone: input.company_phone?.trim() || null,
        status: input.status || 'active',
        deleted: false,
        // company_no is NOT included - trigger will generate it automatically
      };

      if (import.meta.env.DEV) {
        console.log('[useCompanies] Creating company with payload (without company_no):', payload);
      }

      const { data, error: insertError } = await supabase
        .from('Companies')
        .insert(payload)
        .select('id, organization_id, company_no, company_name, company_email, company_phone, status, deleted, created_at, updated_at')
        .single();

      if (insertError) {
        if (import.meta.env.DEV) {
          console.error('[useCompanies] Insert error details:', {
            code: insertError.code,
            message: insertError.message,
            details: insertError.details,
            hint: insertError.hint,
          });
        }
        throw insertError;
      }

      if (import.meta.env.DEV) {
        console.log('[useCompanies] Company inserted successfully, data:', data);
      }

      const newCompany: Company = {
        id: data.id,
        organization_id: data.organization_id,
        company_no: data.company_no ? data.company_no.toString().trim() : null,
        company_name: (data.company_name || '').toString().trim(),
        company_email: data.company_email ? data.company_email.toString().trim().toLowerCase() : null,
        company_phone: data.company_phone ? data.company_phone.toString().trim() : null,
        status: data.status || 'active',
        deleted: data.deleted || false,
        created_at: data.created_at || undefined,
        updated_at: data.updated_at || undefined,
      };

      if (import.meta.env.DEV) {
        console.log('[useCompanies] Created company:', newCompany);
      }

      await fetchCompanies();
      return newCompany;
    } catch (err: any) {
      const errorMessage = err?.message || 'Error creating company';
      console.error('[useCompanies] Create error:', errorMessage, err);
      throw new Error(errorMessage);
    }
  }, [activeOrganizationId, fetchCompanies]);

  /**
   * Update company
   */
  const updateCompany = useCallback(async (id: string, input: UpdateCompanyInput): Promise<Company> => {
    try {
      const payload: any = {};
      
      if (input.company_name !== undefined) {
        payload.company_name = input.company_name.trim();
      }
      if (input.company_email !== undefined) {
        payload.company_email = input.company_email?.trim().toLowerCase() || null;
      }
      if (input.company_phone !== undefined) {
        payload.company_phone = input.company_phone?.trim() || null;
      }
      if (input.status !== undefined) {
        payload.status = input.status || null;
      }

      const { data, error: updateError } = await supabase
        .from('Companies')
        .update(payload)
        .eq('id', id)
        .eq('organization_id', activeOrganizationId || '')
        .eq('deleted', false)
        .select('id, organization_id, company_no, company_name, company_email, company_phone, status, deleted, created_at, updated_at')
        .single();

      if (updateError) {
        throw updateError;
      }

      const updatedCompany: Company = {
        id: data.id,
        organization_id: data.organization_id,
        company_no: data.company_no ? data.company_no.toString().trim() : null,
        company_name: (data.company_name || '').toString().trim(),
        company_email: data.company_email ? data.company_email.toString().trim().toLowerCase() : null,
        company_phone: data.company_phone ? data.company_phone.toString().trim() : null,
        status: data.status || 'active',
        deleted: data.deleted || false,
        created_at: data.created_at || undefined,
        updated_at: data.updated_at || undefined,
      };

      if (import.meta.env.DEV) {
        console.log('[useCompanies] Updated company:', updatedCompany);
      }

      await fetchCompanies();
      return updatedCompany;
    } catch (err: any) {
      const errorMessage = err?.message || 'Error updating company';
      console.error('[useCompanies] Update error:', errorMessage, err);
      throw new Error(errorMessage);
    }
  }, [activeOrganizationId, fetchCompanies]);

  /**
   * Soft delete company
   */
  const archiveCompany = useCallback(async (id: string): Promise<void> => {
    try {
      const { error: updateError } = await supabase
        .from('Companies')
        .update({ deleted: true })
        .eq('id', id)
        .eq('organization_id', activeOrganizationId || '')
        .eq('deleted', false);

      if (updateError) {
        throw updateError;
      }

      if (import.meta.env.DEV) {
        console.log('[useCompanies] Archived company:', id);
      }

      await fetchCompanies();
    } catch (err: any) {
      const errorMessage = err?.message || 'Error archiving company';
      console.error('[useCompanies] Archive error:', errorMessage, err);
      throw new Error(errorMessage);
    }
  }, [activeOrganizationId, fetchCompanies]);

  /**
   * Refetch companies
   */
  const refetch = useCallback(() => {
    fetchCompanies();
  }, [fetchCompanies]);

  // Auto-fetch cuando cambia organization
  useEffect(() => {
    fetchCompanies();
  }, [fetchCompanies]);

  return {
    companies,
    isLoading,
    error,
    fetchCompanies,
    createCompany,
    updateCompany,
    archiveCompany,
    refetch,
  };
}
