-- ====================================================
-- Migration: Seed BOMTemplates for Shades (Roller, Dual, Triple)
-- ====================================================
-- This migration creates BOMTemplates and BOMComponents for:
-- - Roller Shade (Manual/Motorized) - 4 templates
-- - Dual Shade (Manual/Motorized) - 4 templates  
-- - Triple Shade (Manual/Motorized) - 4 templates
-- 
-- Each shade type has multiple template variants:
-- - BASE (standard configuration)
-- - CASSETTE (with cassette hardware, replaces brackets)
-- - SIDE_CHANNEL_ONLY (with side channels only)
-- - SIDE_PLUS_BOTTOM_CHANNEL (with side + bottom channels)
-- ====================================================

DO $$
DECLARE
    v_org_id uuid;
    v_roller_shade_type_id uuid;
    v_dual_shade_type_id uuid;
    v_triple_shade_type_id uuid;
    v_template_id uuid;
    v_bracket_white_id uuid;
    v_bracket_black_id uuid;
    v_bottom_bar_standard_white_id uuid;
    v_bottom_bar_standard_black_id uuid;
    v_bottom_bar_wrapped_white_id uuid;
    v_bottom_bar_wrapped_black_id uuid;
    v_end_cap_white_id uuid;
    v_end_cap_black_id uuid;
    v_manual_drive_id uuid;
    v_motor_drive_id uuid;
    v_cassette_profile_white_id uuid;
    v_cassette_profile_black_id uuid;
    v_cassette_bracket_white_id uuid;
    v_cassette_bracket_black_id uuid;
    v_side_channel_white_id uuid;
    v_side_channel_black_id uuid;
    v_bottom_channel_white_id uuid;
    v_bottom_channel_black_id uuid;
    v_fascia_valance_id uuid;
    v_seq integer;
    v_product_types_table text;
BEGIN
    RAISE NOTICE '🔧 Starting BOM Templates seed for Shades...';
    
    -- Schema inspection
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ProductTypes') THEN
        v_product_types_table := 'ProductTypes';
    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Profiles') THEN
        v_product_types_table := 'Profiles';
    ELSE
        RAISE EXCEPTION 'Neither ProductTypes nor Profiles table found';
    END IF;
    
    SELECT id INTO v_org_id FROM "Organizations" WHERE deleted = false ORDER BY created_at ASC LIMIT 1;
    IF v_org_id IS NULL THEN RAISE EXCEPTION 'No active organization found'; END IF;
    
    -- Get Product Type IDs
    EXECUTE format('SELECT id FROM "%s" WHERE organization_id = $1 AND deleted = false AND (name ILIKE ''%%roller%%shade%%'' OR name = ''Roller Shade'') LIMIT 1', v_product_types_table) INTO v_roller_shade_type_id USING v_org_id;
    EXECUTE format('SELECT id FROM "%s" WHERE organization_id = $1 AND deleted = false AND (name ILIKE ''%%dual%%shade%%'' OR name = ''Dual Shade'') LIMIT 1', v_product_types_table) INTO v_dual_shade_type_id USING v_org_id;
    EXECUTE format('SELECT id FROM "%s" WHERE organization_id = $1 AND deleted = false AND (name ILIKE ''%%triple%%shade%%'' OR name = ''Triple Shade'') LIMIT 1', v_product_types_table) INTO v_triple_shade_type_id USING v_org_id;
    
    -- Resolve Catalog Items
    SELECT id INTO v_bracket_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bracket%' OR item_name ILIKE '%bracket%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') LIMIT 1;
    SELECT id INTO v_bracket_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bracket%' OR item_name ILIKE '%bracket%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') LIMIT 1;
    SELECT id INTO v_bottom_bar_standard_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bottom%bar%' OR item_name ILIKE '%bottom%bar%' OR sku ILIKE '%bottom%rail%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') AND (sku ILIKE '%standard%' OR sku NOT ILIKE '%wrapped%') LIMIT 1;
    SELECT id INTO v_bottom_bar_standard_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bottom%bar%' OR item_name ILIKE '%bottom%bar%' OR sku ILIKE '%bottom%rail%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') AND (sku ILIKE '%standard%' OR sku NOT ILIKE '%wrapped%') LIMIT 1;
    SELECT id INTO v_bottom_bar_wrapped_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bottom%bar%' OR item_name ILIKE '%bottom%bar%' OR sku ILIKE '%bottom%rail%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') AND sku ILIKE '%wrapped%' LIMIT 1;
    SELECT id INTO v_bottom_bar_wrapped_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bottom%bar%' OR item_name ILIKE '%bottom%bar%' OR sku ILIKE '%bottom%rail%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') AND sku ILIKE '%wrapped%' LIMIT 1;
    SELECT id INTO v_end_cap_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%end%cap%' OR item_name ILIKE '%end%cap%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') LIMIT 1;
    SELECT id INTO v_end_cap_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%end%cap%' OR item_name ILIKE '%end%cap%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') LIMIT 1;
    SELECT id INTO v_manual_drive_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%manual%' OR item_name ILIKE '%manual%' OR sku ILIKE '%MECH%') LIMIT 1;
    SELECT id INTO v_motor_drive_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%motor%' OR item_name ILIKE '%motor%' OR sku ILIKE '%CM-%') LIMIT 1;
    SELECT id INTO v_cassette_profile_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%cassette%' OR item_name ILIKE '%cassette%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') LIMIT 1;
    SELECT id INTO v_cassette_profile_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%cassette%' OR item_name ILIKE '%cassette%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') LIMIT 1;
    SELECT id INTO v_side_channel_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%side%channel%' OR item_name ILIKE '%side%channel%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') LIMIT 1;
    SELECT id INTO v_side_channel_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%side%channel%' OR item_name ILIKE '%side%channel%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') LIMIT 1;
    SELECT id INTO v_bottom_channel_white_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bottom%channel%' OR item_name ILIKE '%bottom%channel%') AND (sku ILIKE '%white%' OR item_name ILIKE '%white%') LIMIT 1;
    SELECT id INTO v_bottom_channel_black_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%bottom%channel%' OR item_name ILIKE '%bottom%channel%') AND (sku ILIKE '%black%' OR item_name ILIKE '%black%') LIMIT 1;
    SELECT id INTO v_fascia_valance_id FROM "CatalogItems" WHERE organization_id = v_org_id AND deleted = false AND (sku ILIKE '%fascia%' OR item_name ILIKE '%fascia%' OR sku ILIKE '%valance%' OR item_name ILIKE '%valance%') LIMIT 1;
    
    -- ====================================================
    -- ROLLER SHADE TEMPLATES
    -- ====================================================
    
    IF v_roller_shade_type_id IS NOT NULL THEN
        -- ROLLER_SHADE_BASE
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_roller_shade_type_id, 'Roller Shade - Base', 'Standard Roller Shade BOM', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_roller_shade_type_id AND name = 'Roller Shade - Base' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false);
            RAISE NOTICE '  ✅ Created Roller Shade - Base';
        END IF;
        
        -- ROLLER_SHADE_CASSETTE
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_roller_shade_type_id, 'Roller Shade - Cassette', 'Roller Shade with Cassette', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_roller_shade_type_id AND name = 'Roller Shade - Cassette' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'cassette', v_cassette_profile_white_id, 1, 'm', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'white', CASE WHEN v_cassette_profile_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'cassette', v_cassette_profile_black_id, 1, 'm', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'black', CASE WHEN v_cassette_profile_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_cassette_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'white', CASE WHEN v_cassette_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_cassette_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'black', CASE WHEN v_cassette_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false);
            RAISE NOTICE '  ✅ Created Roller Shade - Cassette';
        END IF;
        
        -- ROLLER_SHADE_SIDE_CHANNEL_ONLY
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_roller_shade_type_id, 'Roller Shade - Side Channel Only', 'Roller Shade with Side Channels', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_roller_shade_type_id AND name = 'Roller Shade - Side Channel Only' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_white_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'white', CASE WHEN v_side_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_black_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'black', CASE WHEN v_side_channel_black_id IS NULL THEN true ELSE false END, false);
            RAISE NOTICE '  ✅ Created Roller Shade - Side Channel Only';
        END IF;
        
        -- ROLLER_SHADE_SIDE_PLUS_BOTTOM_CHANNEL
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_roller_shade_type_id, 'Roller Shade - Side + Bottom Channel', 'Roller Shade with Side and Bottom Channels', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_roller_shade_type_id AND name = 'Roller Shade - Side + Bottom Channel' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_white_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'white', CASE WHEN v_side_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_black_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'black', CASE WHEN v_side_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_bottom_channel_white_id, 1, 'm', v_seq, 'side_channel', '{"side_channel": true, "side_channel_type": "side_and_bottom"}'::jsonb, true, 'white', CASE WHEN v_bottom_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_bottom_channel_black_id, 1, 'm', v_seq, 'side_channel', '{"side_channel": true, "side_channel_type": "side_and_bottom"}'::jsonb, true, 'black', CASE WHEN v_bottom_channel_black_id IS NULL THEN true ELSE false END, false);
            RAISE NOTICE '  ✅ Created Roller Shade - Side + Bottom Channel';
        END IF;
    END IF;
    
    -- ====================================================
    -- DUAL SHADE TEMPLATES (with fascia/valance)
    -- ====================================================
    
    IF v_dual_shade_type_id IS NOT NULL THEN
        -- DUAL_SHADE_BASE
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_dual_shade_type_id, 'Dual Shade - Base', 'Standard Dual Shade BOM with Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_dual_shade_type_id AND name = 'Dual Shade - Base' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Dual Shade - Base';
        END IF;
        
        -- DUAL_SHADE_CASSETTE (same as BASE + cassette components)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_dual_shade_type_id, 'Dual Shade - Cassette', 'Dual Shade with Cassette and Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_dual_shade_type_id AND name = 'Dual Shade - Cassette' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'cassette', v_cassette_profile_white_id, 1, 'm', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'white', CASE WHEN v_cassette_profile_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'cassette', v_cassette_profile_black_id, 1, 'm', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'black', CASE WHEN v_cassette_profile_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_cassette_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'white', CASE WHEN v_cassette_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_cassette_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'black', CASE WHEN v_cassette_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Dual Shade - Cassette';
        END IF;
        
        -- DUAL_SHADE_SIDE_CHANNEL_ONLY (same as BASE + side channels + fascia)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_dual_shade_type_id, 'Dual Shade - Side Channel Only', 'Dual Shade with Side Channels and Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_dual_shade_type_id AND name = 'Dual Shade - Side Channel Only' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_white_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'white', CASE WHEN v_side_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_black_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'black', CASE WHEN v_side_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Dual Shade - Side Channel Only';
        END IF;
        
        -- DUAL_SHADE_SIDE_PLUS_BOTTOM_CHANNEL (same as SIDE_CHANNEL_ONLY + bottom channel)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_dual_shade_type_id, 'Dual Shade - Side + Bottom Channel', 'Dual Shade with Side/Bottom Channels and Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_dual_shade_type_id AND name = 'Dual Shade - Side + Bottom Channel' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_white_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'white', CASE WHEN v_side_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_black_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'black', CASE WHEN v_side_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_bottom_channel_white_id, 1, 'm', v_seq, 'side_channel', '{"side_channel": true, "side_channel_type": "side_and_bottom"}'::jsonb, true, 'white', CASE WHEN v_bottom_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_bottom_channel_black_id, 1, 'm', v_seq, 'side_channel', '{"side_channel": true, "side_channel_type": "side_and_bottom"}'::jsonb, true, 'black', CASE WHEN v_bottom_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Dual Shade - Side + Bottom Channel';
        END IF;
    END IF;
    
    -- ====================================================
    -- TRIPLE SHADE TEMPLATES (with fascia/valance)
    -- ====================================================
    
    IF v_triple_shade_type_id IS NOT NULL THEN
        -- TRIPLE_SHADE_BASE (same as DUAL_SHADE_BASE)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_triple_shade_type_id, 'Triple Shade - Base', 'Standard Triple Shade BOM with Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_triple_shade_type_id AND name = 'Triple Shade - Base' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Triple Shade - Base';
        END IF;
        
        -- TRIPLE_SHADE_CASSETTE (same as DUAL_SHADE_CASSETTE pattern)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_triple_shade_type_id, 'Triple Shade - Cassette', 'Triple Shade with Cassette and Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_triple_shade_type_id AND name = 'Triple Shade - Cassette' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'cassette', v_cassette_profile_white_id, 1, 'm', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'white', CASE WHEN v_cassette_profile_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'cassette', v_cassette_profile_black_id, 1, 'm', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'black', CASE WHEN v_cassette_profile_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_cassette_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'white', CASE WHEN v_cassette_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_cassette_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": true}'::jsonb, true, 'black', CASE WHEN v_cassette_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Triple Shade - Cassette';
        END IF;
        
        -- TRIPLE_SHADE_SIDE_CHANNEL_ONLY (same as DUAL_SHADE_SIDE_CHANNEL_ONLY pattern)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_triple_shade_type_id, 'Triple Shade - Side Channel Only', 'Triple Shade with Side Channels and Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_triple_shade_type_id AND name = 'Triple Shade - Side Channel Only' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_white_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'white', CASE WHEN v_side_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_black_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'black', CASE WHEN v_side_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Triple Shade - Side Channel Only';
        END IF;
        
        -- TRIPLE_SHADE_SIDE_PLUS_BOTTOM_CHANNEL (same as DUAL_SHADE_SIDE_PLUS_BOTTOM_CHANNEL pattern)
        INSERT INTO "BOMTemplates" (organization_id, product_type_id, name, description, active, deleted)
        VALUES (v_org_id, v_triple_shade_type_id, 'Triple Shade - Side + Bottom Channel', 'Triple Shade with Side/Bottom Channels and Fascia/Valance', true, false)
        ON CONFLICT DO NOTHING RETURNING id INTO v_template_id;
        IF v_template_id IS NULL THEN SELECT id INTO v_template_id FROM "BOMTemplates" WHERE organization_id = v_org_id AND product_type_id = v_triple_shade_type_id AND name = 'Triple Shade - Side + Bottom Channel' AND deleted = false; END IF;
        IF v_template_id IS NOT NULL THEN
            DELETE FROM "BOMComponents" WHERE bom_template_id = v_template_id;
            v_seq := 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_manual_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "manual"}'::jsonb, false, CASE WHEN v_manual_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'operating_system_drive', v_motor_drive_id, 1, 'ea', v_seq, 'drive', '{"drive_type": "motor"}'::jsonb, false, CASE WHEN v_motor_drive_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'tube', NULL, 1, 'm', v_seq, NULL, NULL, false, true, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_white_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'white', CASE WHEN v_bracket_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bracket', v_bracket_black_id, 2, 'ea', v_seq, 'cassette', '{"cassette": false}'::jsonb, true, 'black', CASE WHEN v_bracket_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_standard_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_standard_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "standard"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_standard_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_white_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'white', CASE WHEN v_bottom_bar_wrapped_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_bar', v_bottom_bar_wrapped_black_id, 1, 'm', v_seq, 'bottom_rail', '{"bottom_rail_type": "wrapped"}'::jsonb, true, 'black', CASE WHEN v_bottom_bar_wrapped_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_white_id, 2, 'ea', v_seq, NULL, NULL, true, 'white', CASE WHEN v_end_cap_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'bottom_rail_end_cap', v_end_cap_black_id, 2, 'ea', v_seq, NULL, NULL, true, 'black', CASE WHEN v_end_cap_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_white_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'white', CASE WHEN v_side_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_side_channel_black_id, 2, 'm', v_seq, 'side_channel', '{"side_channel": true}'::jsonb, true, 'black', CASE WHEN v_side_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_bottom_channel_white_id, 1, 'm', v_seq, 'side_channel', '{"side_channel": true, "side_channel_type": "side_and_bottom"}'::jsonb, true, 'white', CASE WHEN v_bottom_channel_white_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, hardware_color, auto_select, deleted) VALUES (v_template_id, v_org_id, 'side_channel_profile', v_bottom_channel_black_id, 1, 'm', v_seq, 'side_channel', '{"side_channel": true, "side_channel_type": "side_and_bottom"}'::jsonb, true, 'black', CASE WHEN v_bottom_channel_black_id IS NULL THEN true ELSE false END, false); v_seq := v_seq + 10;
            IF v_fascia_valance_id IS NOT NULL THEN INSERT INTO "BOMComponents" (bom_template_id, organization_id, component_role, component_item_id, qty_per_unit, uom, sequence_order, block_type, block_condition, applies_color, auto_select, deleted) VALUES (v_template_id, v_org_id, NULL, v_fascia_valance_id, 1, 'm', v_seq, NULL, NULL, false, false, false); END IF;
            RAISE NOTICE '  ✅ Created Triple Shade - Side + Bottom Channel';
        END IF;
    END IF;
    
    RAISE NOTICE '✅ Migration completed!';
    RAISE NOTICE '';
    RAISE NOTICE '📝 NOTE: Some catalog items may not have been found.';
    RAISE NOTICE '   Components with auto_select=true will be resolved at runtime.';
    RAISE NOTICE '   Components with NULL component_item_id need manual assignment.';
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Error: %', SQLERRM;
END $$;

-- ====================================================
-- VERIFICATION QUERIES (commented - uncomment to test)
-- ====================================================

/*
-- Count templates created
SELECT 
    pt.name as product_type,
    bt.name as template_name,
    COUNT(bc.id) as component_count
FROM "BOMTemplates" bt
INNER JOIN "ProductTypes" pt ON pt.id = bt.product_type_id
LEFT JOIN "BOMComponents" bc ON bc.bom_template_id = bt.id AND bc.deleted = false
WHERE bt.deleted = false
GROUP BY pt.name, bt.name
ORDER BY pt.name, bt.name;

-- Sample components for a template
SELECT 
    bc.sequence_order,
    bc.component_role,
    ci.sku,
    ci.item_name,
    bc.qty_per_unit,
    bc.uom,
    bc.block_type,
    bc.block_condition,
    bc.applies_color,
    bc.hardware_color,
    bc.auto_select
FROM "BOMComponents" bc
LEFT JOIN "CatalogItems" ci ON ci.id = bc.component_item_id
INNER JOIN "BOMTemplates" bt ON bt.id = bc.bom_template_id
WHERE bt.name = 'Roller Shade - Base'
  AND bc.deleted = false
ORDER BY bc.sequence_order;
*/

